function [fitresult, gof] = createFit1(time, loadArray)
%CREATEFIT1(TIME,LOADARRAY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: time
%      Y Output: loadArray
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Dec-2023 02:40:37


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( time, loadArray );

% Set up fittype and options.
ft = fittype( 'sin4' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [2055.9228673324 0.0341490350720557 -2.40153870150973 892.615827924707 0.0682980701441113 -3.09681931053119 203.673202056342 0.136596140288223 -1.60362137766021 143.995685258397 6.28342245325824 -1.58469380927711];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'loadArray vs. time', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'time', 'Interpreter', 'none' );
ylabel( 'loadArray', 'Interpreter', 'none' );
grid on


